remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Sarah Criswell Portfolio
description: "It's easier to ask forgiveness than it is to get permission. Building innovative software with a relentless pursuit of progress. Welcome to my portfolio."
author:
  name: Sarah Criswell
  email: sarcri2328@students.ecpi.edu
